name: "Build and Release"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build Application"
    runs-on: ubuntu-latest

    steps:
      - name: "Print Working Directory"
        run: pwd

      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "List contents working directory"
        run: ls -liFh

      - name: "Create a file with specifc content"
        run: git rev-parse --short HEAD > short_commit_id

      - name: "List contents working directory"
        run: ls -liFh

      - name: "Print content of the above file"
        run: cat short_commit_id

      - name: "Persist the github workspace"
        id: persist-workspace
        uses: actions/cache/save@v4
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}-persist-workspace-key

  release:
    name: "Release Application"
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: "Persist the github workspace"
        uses: actions/cache/restore@v4
        id: restore-workspace
        with:
          path: ${{ github.workspace }}
          key: ${{ github.sha }}-persist-workspace-key

      - name: "Print Working Directory"
        run: pwd

      - name: "List contents working directory"
        run: ls -liFh

      - name: "Print content of the above file"
        run: cat short_commit_id

      - name: "Get full commit id from file"
        run: |
          export OUR_COMMIT_ID=$(cat short_commit_id)
          git rev-parse ${OUR_COMMIT_ID}

      - name: "Remove the persistant workspace we created"
        uses: actions/adapttive-cache-delete
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          cache-key: ${{ github.sha }}-persist-workspace-key
