name: "Build and Release"

on:
  push:
    branches:
      - main

jobs:
  build:
    name: "Build Application"
    runs-on: ubuntu-latest

    steps:
      - name: "Print Working Directory"
        run: pwd

      - name: "Checkout code"
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: "List contents working directory"
        run: ls -liFh

      - name: "List contents github workspace directory"
        run: ls -liFh /github

      - name: "Create a file with specifc content"
        run: git rev-parse --short HEAD > short_commit_id

      - name: "Copy above file to github workspace"
        run: cp short_commit_id /github/workspace

      - name: "List contents working directory"
        run: ls -liFh

      - name: "List contents github workspace"
        run: ls -liFh /github/workspace

      - name: "Print content of the above file"
        run: cat short_commit_id

  release:
    name: "Release Application"
    needs: build
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: "Print Working Directory"
        run: pwd

      - name: "List contents working directory"
        run: ls -liFh

      - name: "List contents github workspace"
        run: ls -liFh /github/workspace

      - name: "Print content of the above file"
        run: cat short_commit_id

      - name: "Get full commit id from file"
        run: |
          export OUR_COMMIT_ID=$(cat short_commit_id)
          git rev-parse ${OUR_COMMIT_ID}

